// AUTO-GENERATED from user-provided exam objectives PDFs.
export const OBJECTIVES = {
  "220-1201": {
    "1.1": {
      "domain": "1.0 Mobile Devices",
      "title": "Compare and contrast accessories and connectivity options for mobile devices.",
      "bullets": [
        "Connection methods",
        "Universal Serial Bus (USB)/USB-C/microUSB/miniUSB",
        "Lightning",
        "Near-field communication (NFC)",
        "Bluetooth",
        "Tethering/hotspot",
        "Accessories",
        "Stylus",
        "Headsets",
        "Speakers",
        "Webcam\u2022 Docking station",
        "Port replicator",
        "Trackpad/drawing pad/track points"
      ]
    },
    "1.2": {
      "domain": "1.0 Mobile Devices",
      "title": "Given a scenario, configure basic mobile device network connectivity and provide application support.",
      "bullets": [
        "Wireless/cellular data network (enable/disable)",
        "3G/4G/5G",
        "Hotspot",
        "Wi-Fi",
        "Subscriber Identity Module (SIM)/eSIM",
        "Bluetooth",
        "Enable Bluetooth",
        "Enable pairing",
        "Find a device for pairing",
        "Enter the appropriate personal identification number (PIN) code",
        "Test connectivity\u2022 Location services",
        "Global positioning system (GPS) services",
        "Cellular location services",
        "Mobile device management (MDM)",
        "Device configurations \u25e6 Corporate \u25e6 Bring your own device (BYOD)",
        "Policy enforcement",
        "Corporate applications",
        "Mobile device synchronization",
        "Recognizing data caps",
        "Calendar \u2212Contacts",
        "Business applications \u25e6Mail \u25e6Cloud storage"
      ]
    },
    "1.3": {
      "domain": "1.0 Mobile Devices",
      "title": "Objective 1.3",
      "bullets": [
        "Ports and protocols",
        "20-21 \u2013 File Transfer Protocol (FTP)",
        "22 \u2013 Secure Shell (SSH)",
        "23 \u2013 Telnet",
        "25 \u2013 Simple Mail Transfer Protocol (SMTP)",
        "53 \u2013 Domain Name System (DNS)",
        "67/68 \u2013 Dynamic Host Configuration Protocol (DHCP) \u221280 \u2013 Hypertext Transfer Protocol (HTTP)",
        "110 \u2013 Post Office Protocol 3 (POP3)",
        "143 \u2013 Internet Mail Access Protocol (IMAP)",
        "137-139 Network Basic Input/ Output System (NetBIOS)/ NetBIOS over TCP/IP (NetBT)",
        "389 \u2013 Lightweight Directory Access Protocol (LDAP)",
        "443 \u2013 Hypertext Transfer Protocol Secure (HTTPS)",
        "445 \u2013 Server Message Block (SMB)/ Common Internet File System (CIFS)",
        "3389 \u2013 Remote Desktop Protocol (RDP)",
        "TCP vs. UDP Explain wireless networking technologies.",
        "Frequencies",
        "2.4GHz",
        "5GHz",
        "6GHz \u2022 Channels",
        "Regulations",
        "Channel selection \u25e6Widths \u25e6Frequencies \u25e6 Bands\u2022 Bluetooth",
        "802.11 standards",
        "NFC",
        "Radio-frequency identification (RFID) 2.0 Networking Summarize services provided by networked hosts.",
        "Server roles",
        "DNS",
        "DHCP",
        "Fileshare",
        "Print servers",
        "Mail servers",
        "Syslog",
        "Web servers",
        "Authentication, Authorization, and Accounting (AAA)",
        "Database servers",
        "Network Time Protocol (NTP)\u2022 Internet appliances",
        "Spam gateways",
        "Unified threat management (UTM)",
        "Load balancers",
        "Proxy servers",
        "Legacy/embedded systems",
        "Supervisory control and data acquisition (SCADA)",
        "Internet of Things (IoT) devices"
      ]
    },
    "2.3": {
      "domain": "2.0 Networking",
      "title": "Objective 2.3",
      "bullets": [
        "DNS",
        "A",
        "AAAA",
        "Canonical Name (CNAME)",
        "Mail exchanger (MX)",
        "Text (TXT) \u25e6Spam management \u0568DomainKeys Identified Mail (DKIM) \u0568Sender Policy Framework (SPF) \u0568Domain-based Message Authentication, Reporting, and Conformance (DMARC)",
        "DHCP",
        "Leases",
        "Reservations",
        "Scope",
        "Exclusions\u2022 Virtual LAN [local area network] (VLAN)",
        "Virtual private network (VPN) Compare and contrast common networking hardware devices.",
        "Routers",
        "Switches",
        "Managed",
        "Unmanaged",
        "Access points",
        "Patch panel",
        "Firewall",
        "Power over Ethernet (PoE)",
        "Injectors",
        "Switch",
        "PoE standards\u2022 Cable modem",
        "Digital subscriber line (DSL)",
        "Optical network terminal (ONT)",
        "Network interface card (NIC)",
        "Physical media access control (MAC) address Given a scenario, configure basic wired/wireless small office/home office (SOHO) networks.",
        "Internet Protocol (IP) addressing",
        "IPv4 \u25e6Private addresses \u25e6 Public addresses",
        "IPv6",
        "Automatic Private IP Addressing (APIPA)",
        "Static",
        "Dynamic",
        "Subnet mask",
        "Gateway 2.0 | Networking"
      ]
    },
    "2.6": {
      "domain": "2.0 Networking",
      "title": "Objective 2.6",
      "bullets": [
        "Internet connection types",
        "Satellite",
        "Fiber",
        "Cable",
        "DSL",
        "Cellular",
        "Wireless internet service provider (WISP)\u2022 Network types",
        "LAN",
        "Wide area network (WAN)",
        "Personal area network (PAN)",
        "Metropolitan area network (MAN)",
        "Storage area network (SAN)",
        "Wireless local area network (WLAN) Explain networking tools and their purposes.",
        "Crimper",
        "Cable stripper",
        "Wi-Fi analyzer",
        "Toner probe\u2022 Punchdown tool",
        "Cable tester",
        "Loopback plug",
        "Network tap 2.0 | Networking Exam Objectives Document Version 4.0 Copyright \u00a9 2024 CompTIA, Inc. All rights reserved.Compare and contrast display components and attributes.",
        "Types",
        "Liquid crystal display (LCD) \u25e6In-plane switching (IPS) \u25e6Twisted nematic (TN) \u25e6Vertical alignment (VA)",
        "Organic light-emitting diode (OLED)",
        "Mini light-emitting diode (Mini-LED)\u2022 Touch screen/digitizer",
        "Inverter",
        "Attributes",
        "Pixel density",
        "Refresh rates",
        "Screen resolution",
        "Color gamut Summarize basic cable types and their connectors, features, and purposes.",
        "Network cables",
        "Copper \u25e6Categories \u0568T568A/T568B standards \u25e6Coaxial \u25e6Shielded twisted pair \u0568Direct burial \u25e6Unshielded twisted pair",
        "Plenum-rated",
        "Optical \u25e6Single-mode \u25e6Multimode",
        "Peripheral cables",
        "USB 2.0 \u2212USB 3.0 \u2212Serial \u2212Thunderbolt",
        "Video cables",
        "High-definition Multimedia Interface (HDMI)",
        "DisplayPort",
        "Digital Visual Interface (DVI)",
        "Video Graphics Array (VGA)",
        "USB-C",
        "Hard drive cables",
        "Serial Advanced Technology Attachment (SATA)",
        "External SATA (eSATA)",
        "Adapters",
        "Connector types",
        "RJ11 \u2212RJ45",
        "F-type",
        "Straight tip (ST)",
        "Subscriber connector (SC)",
        "Lucent connector (LC)",
        "Punchdown block",
        "MicroUSB",
        "MiniUSB",
        "USB-C",
        "Molex",
        "Lightning",
        "DB9 3.0 Hardware Compare and contrast RAM characteristics.",
        "Form factors",
        "Small Outline Dual In-line Memory Module (SODIMM)",
        "Dual In-line Memory Module (DIMM)\u2022 Double Data Rate (DDR) iterations",
        "Error-correcting code (ECC) vs. non-ECC RAM",
        "Channel configurations"
      ]
    },
    "3.2": {
      "domain": "3.0 Hardware",
      "title": "Objective 3.2",
      "bullets": [
        "Hard drives",
        "Spindle speeds",
        "Form factors \u25e62.5-inch \u25e63.5-inch",
        "Solid-state drives",
        "Communications interfaces \u25e6Non-volatile Memory Express (NVMe) \u25e6SATA \u25e6Peripheral Component Interconnect Express (PCIe) \u25e6Serial Attached SCSI [Small Computer System Interface] (SAS)",
        "Form factors \u25e6M.2 \u25e6Mini-serial Advanced Technology Attachment (mSATA) \u2022 Drive configurations",
        "Redundant Array of Independent Disks (RAID) 0, 1, 5, 6, 10",
        "Removable storage",
        "Flash drives",
        "Memory cards",
        "Optical drives Given a scenario, install and configure motherboards, central processing units (CPUs), and add-on cards.",
        "Motherboard form factors",
        "Advanced Technology Extended (ATX)",
        "microATX",
        "Information Technology eXtended (ITX)",
        "Motherboard connector types",
        "Peripheral Component Interconnect (PCI)",
        "PCIe",
        "Power connectors",
        "SATA",
        "eSATA",
        "Headers",
        "M.2",
        "Motherboard compatibility",
        "CPU socket types \u25e6Advanced Micro Devices, Inc. (AMD) \u25e6Intel",
        "Multisocket \u2022 BIOS/Unified Extensible Firmware Interface (UEFI) settings",
        "Boot options",
        "USB permissions",
        "Trusted Platform Module (TPM) security features",
        "Fan considerations",
        "Secure Boot",
        "Boot password",
        "BIOS password",
        "Temperature monitoring",
        "Virtualization support",
        "Encryption",
        "TPM",
        "Hardware security module (HSM)",
        "CPU architecture",
        "x86/x64",
        "Advanced RISC [Reduced Instruction Set Computer] Machine (ARM)",
        "Core configurations\u2022 Expansion cards",
        "Sound card",
        "Video card",
        "Capture card",
        "Network interface card",
        "Cooling",
        "Fans",
        "Heat sink",
        "Thermal paste/pads",
        "Liquid 3.0 | Hardware"
      ]
    },
    "3.5": {
      "domain": "3.0 Hardware",
      "title": "Given a scenario, install the appropriate power supply.",
      "bullets": [
        "Input 110\u2013120 VAC vs. 220\u2013240 VAC",
        "Output 3.3V vs. 5V vs. 12V",
        "20+4 pin motherboard connector",
        "Redundant power supply\u2022 Modular power supply",
        "Wattage rating",
        "Energy efficiency"
      ]
    },
    "3.6": {
      "domain": "3.0 Hardware",
      "title": "Objective 3.6",
      "bullets": [
        "Properly unbox device and consider set-up location",
        "Use appropriate drivers for a given operating system",
        "Printer Control Language (PCL) vs. postscript",
        "Firmware",
        "Device connectivity",
        "USB",
        "Ethernet",
        "Wireless\u2022 Public/shared devices",
        "Printer share",
        "Print server",
        "Configuration settings",
        "Duplex",
        "Orientation",
        "Tray settings",
        "Quality",
        "Security",
        "User authentication",
        "Badging \u2212Audit logs",
        "Secured prints",
        "Network scan services",
        "Email",
        "SMB",
        "Cloud services",
        "Automatic document feeder (ADF)/flatbed scanner Given a scenario, perform appropriate printer maintenance.",
        "Laser",
        "Maintenance: Replace toner, apply maintenance kit, calibrate, and clean",
        "Inkjet",
        "Ink cartridge, printhead, roller, and feeder",
        "Maintenance: Clean printheads, replace cartridges, calibrate, and clear jams\u2022 Thermal",
        "Feed assembly",
        "Special thermal paper",
        "Maintenance: Replace paper, clean heating element, and remove debris",
        "Impact",
        "Multipart paper",
        "Maintenance: Replace ribbon, printhead, and paper 3.0 | Hardware"
      ]
    },
    "3.8": {
      "domain": "3.0 Hardware",
      "title": "Objective 3.8",
      "bullets": [
        "Purpose of virtual machines",
        "Sandbox",
        "Test development",
        "Application virtualization \u25e6Legacy software/OS \u25e6Cross-platform virtualization",
        "Requirements",
        "Security",
        "Network",
        "Storage\u2022 Desktop virtualization",
        "Virtual Desktop Infrastructure (VDI)",
        "Containers",
        "Hypervisors",
        "Type 1",
        "Type 2 Summarize cloud computing concepts.",
        "Common cloud models",
        "Private cloud",
        "Public cloud",
        "Hybrid cloud",
        "Community cloud",
        "Infrastructure as a service (IaaS)",
        "Software as a service (SaaS)",
        "Platform as a service (PaaS)\u2022 Cloud characteristics",
        "Shared resources vs. dedicated resources",
        "Metered utilization \u25e6Ingress/egress",
        "Elasticity",
        "Availability",
        "File synchronization",
        "Multitenancy 4.0 Virtualization and Cloud Computing"
      ]
    },
    "4.2": {
      "domain": "4.0 Virtualization and Cloud Computing",
      "title": "Objective 4.2",
      "bullets": [
        "Common symptoms",
        "Power-on self-test (POST) beeps",
        "Proprietary crash screens",
        "Blank screen",
        "No power \u2212Sluggish performance",
        "Overheating",
        "Burning smell",
        "Random shutdown",
        "Application crashes \u2212Unusual noise",
        "Capacitor swelling",
        "Inaccurate system date/time Given a scenario, troubleshoot drive and RAID issues.",
        "Common symptoms",
        "Light-emitting diode (LED) status indicators",
        "Grinding noises",
        "Clicking sounds",
        "Bootable device not found",
        "Data loss/corruption \u2212RAID failure",
        "Self-monitoring and Reporting Technology (S.M.A.R.T.) failure",
        "Extended read/write times",
        "Low performance input/output operations per second (IOPS)",
        "Missing drives in OS \u2212Array missing",
        "Audible alarms 5.0 Hardware and Network Troubleshooting"
      ]
    },
    "5.2": {
      "domain": "5.0 Hardware and Network Troubleshooting",
      "title": "Given a scenario, troubleshoot video, projector, and display issues.",
      "bullets": [
        "Common symptoms",
        "Incorrect input source",
        "Physical cabling issues",
        "Burnt-out bulb",
        "Fuzzy image \u2212Display burn-in",
        "Dead pixels",
        "Flashing screen",
        "Incorrect color display",
        "Audio issues \u2212Dim image",
        "Intermittent projector shutdown",
        "Sizing issues",
        "Distorted image Given a scenario, troubleshoot common mobile device issues.",
        "Common symptoms",
        "Poor battery health",
        "Swollen battery",
        "Broken screen",
        "Improper charging",
        "Poor/no connectivity \u2212Liquid damage",
        "Overheating",
        "Digitizer issues",
        "Physically damaged ports",
        "Malware",
        "Cursor drift/touch calibration \u2212Unable to install new applications",
        "Stylus does not work",
        "Degraded performance"
      ]
    },
    "5.4": {
      "domain": "5.0 Hardware and Network Troubleshooting",
      "title": "Objective 5.4",
      "bullets": [
        "Common symptoms",
        "Intermittent wireless connectivity",
        "Slow network speeds",
        "Limited connectivity",
        "Jitter",
        "Poor Voice over Internet Protocol (VoIP) quality \u2212Port flapping",
        "High latency",
        "External interference",
        "Authentication failures",
        "Intermittent internet connectivity Given a scenario, troubleshoot printer issues.",
        "Lines down the printed pages",
        "Garbled print",
        "Paper jams",
        "Faded prints",
        "Paper not feeding",
        "Multipage misfeed",
        "Multiple prints pending in queue\u2022 Speckling on printed pages",
        "Double/echo images on the print",
        "Grinding noise",
        "Finishing issues",
        "Staple jams",
        "Hole punch\u2022 Incorrect page orientation",
        "Tray not recognized",
        "Connectivity issues",
        "Frozen print queue 5.0 | Hardware and Network Troubleshooting"
      ]
    },
    "5.6": {
      "domain": "5.0 Hardware and Network Troubleshooting",
      "title": "Objective 5.6",
      "bullets": [
        "Apple tablet/smartphone",
        "Android tablet/smartphone",
        "Windows tablet",
        "Chromebook",
        "Windows laptop/Mac laptop/ Linux laptop",
        "Windows desktop/Mac desktop/ Linux desktop",
        "Windows server with Active Directory and Print Manager",
        "Monitors",
        "Projectors",
        "SOHO router/switch",
        "Access point",
        "VoIP phone",
        "Printer",
        "Laser/inkjet",
        "Wireless",
        "3-D printer",
        "Thermal",
        "Surge suppressor",
        "UPS",
        "Smart devices (IoT devices)",
        "Server with a hypervisor",
        "Punchdown block",
        "Patch panel",
        "Webcams",
        "Speakers",
        "MicrophonesSPARE PARTS/HARDWARE",
        "Motherboards",
        "RAM",
        "Hard drives",
        "Power supplies",
        "Video cards",
        "Sounds cards",
        "Network cards",
        "Wireless NICs",
        "Fans/cooling devices/heat sink",
        "CPUs",
        "Assorted connectors/cables",
        "USB",
        "HDMI",
        "DisplayPort",
        "DVI",
        "VGA",
        "Adapters",
        "Bluetooth adapter",
        "Network cables",
        "Unterminated network cable/connectors",
        "AC adapters",
        "Optical drives",
        "Screws/stand-offs",
        "Cases",
        "Maintenance kit",
        "Mice/keyboards",
        "Keyboard-Video-Mouse (KVM)",
        "Console cable",
        "SSDTOOLS",
        "Screwdrivers",
        "Multimeter",
        "Wire cutters",
        "Punchdown tool",
        "Crimper",
        "Power supply tester",
        "Cable stripper",
        "Standard technician toolkit",
        "Electrostatic discharge (ESD) strap",
        "Thermal paste",
        "Cable tester",
        "Cable toner",
        "Wi-Fi analyzer",
        "Serial Advanced Technology Attachment (SATA) to USB connectors SOFTWARE",
        "Operating systems",
        "LinuxCompTIA has included this sample list of hardware and software to assist candidates as they prepare for the A+ Core 1 (220-1201) certification exam. This list may also be helpful for training companies that wish to create a lab component for their training offering. The bulleted lists below each topic are sample lists and are not exhaustive.CompTIA A+ Core 1 (220-1201) Hardware and Software List \u00a9 2024 CompTIA, Inc., used under license by CompTIA, Inc. All rights reserved. All certification programs and education related to such programs are operated exclusively by CompTIA, Inc. CompTIA is a registered trademark of CompTIA, Inc. in the U.S. and internationally. Other brands and company names mentioned herein may be trademarks or service marks of CompTIA, Inc. or of their respective owners. Reproduction or dissemination prohibited without the written consent of CompTIA, Inc. Printed in the U.S. 11273-May2024"
      ]
    }
  },
  "220-1202": {
    "1.1": {
      "domain": "1.0 Operating Systems",
      "title": "Given a scenario, perform OS installations and upgrades in a diverse environment.",
      "bullets": [
        "Boot methods",
        "Universal Serial Bus (USB)",
        "Network",
        "Solid-state/flash drives",
        "Internet-based",
        "External/hot-swappable drive",
        "Internal hard drive (partition)",
        "Multiboot",
        "Types of installations",
        "Clean install",
        "Upgrade \u2212Image deployment",
        "Remote network installation",
        "Zero-touch deployment",
        "Recovery partition",
        "Repair installation",
        "Other considerations \u0563Third-party drivers",
        "Partitioning",
        "GUID [globally unique identifier] Partition Table (GPT)",
        "Master boot record (MBR)\u2022 Drive format",
        "Upgrade considerations",
        "Backup files and user preferences",
        "Application and driver support/ backward compatibility",
        "Hardware compatibility",
        "Feature updates",
        "Product life cycle"
      ]
    },
    "1.2": {
      "domain": "1.0 Operating Systems",
      "title": "Compare and contrast basic features of Microsoft Windows editions.",
      "bullets": [
        "Windows 10 editions",
        "Home",
        "Pro",
        "Pro for Workstations",
        "Enterprise",
        "Windows 11 editions",
        "Home",
        "Pro",
        "Enterprise\u2022 N versions",
        "Feature differences",
        "Domain vs. workgroup",
        "Desktop styles/user interface",
        "Availability of Remote Desktop Protocol (RDP)",
        "Random-access memory (RAM) support limitations",
        "BitLocker",
        "gpedit.msc\u2022 Upgrade paths",
        "In-place upgrade",
        "Clean install",
        "Hardware requirements",
        "Trusted Platform Module (TPM)",
        "Unified Extensible Firmware Interface (UEFI)"
      ]
    },
    "1.3": {
      "domain": "1.0 Operating Systems",
      "title": "Objective 1.3",
      "bullets": [
        "Task Manager",
        "Services",
        "Startup",
        "Performance",
        "Processes",
        "Users",
        "Microsoft Management Console (MMC) snap-in",
        "Event Viewer (eventvwr.msc)",
        "Disk Management (diskmgmt.msc)",
        "Task Scheduler (taskschd.msc) \u2212Device Manager (devmgmt.msc)",
        "Certificate Manager (certmgr.msc)",
        "Local User and Groups (lusrmgr.msc)",
        "Performance Monitor (perfmon.msc)",
        "Group Policy Editor (gpedit.msc)",
        "Additional tools",
        "System Information (msinfo32. exe)",
        "Resource Monitor (resmon.exe)",
        "System Configuration (msconfig. exe) \u2212Disk Cleanup (cleanmgr.exe)",
        "Disk Defragment (dfrgui.exe)",
        "Registry Editor (regedit.exe)1.4 1.0 | Operating Systems Given a scenario, use the appropriate Microsoft command-line tools.",
        "Navigation",
        "cd",
        "dir",
        "Network",
        "ipconfig",
        "ping",
        "netstat",
        "nslookup",
        "net use",
        "tracert",
        "pathping\u2022 Disk management",
        "chkdsk",
        "format",
        "diskpart",
        "File management",
        "md",
        "rmdir",
        "robocopy",
        "Informational",
        "hostname",
        "net user \u2212winver",
        "whoami",
        "[command name] /?",
        "OS management",
        "gpupdate",
        "gpresult",
        "sfc"
      ]
    },
    "1.5": {
      "domain": "1.0 Operating Systems",
      "title": "Given a scenario, configure Microsoft Windows settings.",
      "bullets": [
        "Internet Options",
        "Devices and Printers",
        "Program and Features",
        "Network and Sharing Center",
        "System",
        "Windows Defender Firewall",
        "Mail",
        "Sound",
        "User Accounts",
        "Device Manager",
        "Indexing Options",
        "Administrative Tools \u2022 File Explorer Options",
        "View hidden files",
        "Hide extensions",
        "General options",
        "View options",
        "Power Options",
        "Hibernate",
        "Power plans",
        "Sleep/suspend",
        "Standby",
        "Choose what closing the lid does",
        "Turn on fast startup \u2212USB selective suspend",
        "Ease of Access",
        "Time and Language",
        "Update and Security",
        "Personalization",
        "Apps",
        "Privacy",
        "System",
        "Devices",
        "Network and Internet",
        "Gaming",
        "Accounts"
      ]
    },
    "1.6": {
      "domain": "1.0 Operating Systems",
      "title": "Objective 1.6",
      "bullets": [
        "Domain joined vs. workgroup",
        "Shared resources",
        "Printers",
        "File servers",
        "Mapped drives",
        "Local OS firewall settings",
        "Application restrictions and exceptions",
        "Configuration",
        "Client network configuration",
        "Internet Protocol (IP) addressing scheme",
        "Domain Name System (DNS) settings",
        "Subnet mask",
        "Gateway",
        "Static vs. dynamic\u2022 Establish network connections",
        "Virtual private network (VPN)",
        "Wireless",
        "Wired",
        "Wireless wide area network (WWAN)/cellular network",
        "Proxy settings",
        "Public network vs. private network",
        "File Explorer navigation\u2013network paths",
        "Metered connections and limitations Explain common features and tools of the macOS/desktop operating system.",
        "Installation and uninstallation of applications",
        "File types \u0563 .dmg \u0563 .pkg \u0563 .app",
        "App Store",
        "Uninstallation process",
        "System folders",
        "/Applications",
        "/Users",
        "/Library",
        "/System",
        "/Users/Library",
        "Apple ID and corporate restrictions",
        "Best practices",
        "Backups",
        "Antivirus",
        "Updates/patches",
        "Rapid Security Response (RSR)\u2022 System Preferences",
        "Displays",
        "Networks",
        "Printers",
        "Scanners",
        "Privacy",
        "Accessibility",
        "Time Machine",
        "Features",
        "Multiple desktops",
        "Mission Control",
        "Keychain",
        "Spotlight",
        "iCloud \u0563 iMessage \u0563FaceTime \u0563Drive",
        "Gestures",
        "Finder",
        "Dock",
        "Continuity\u2022 Disk Utility",
        "FileVault",
        "Terminal",
        "Force Quit 1.0 | Operating Systems Exam Objectives Document Version 4.0",
        "File management",
        "ls",
        "pwd",
        "mv",
        "cp",
        "rm",
        "chmod",
        "chown",
        "grep",
        "find",
        "Filesystem management",
        "fsck",
        "mount",
        "Administrative",
        "su",
        "sudo\u2022 Package management",
        "apt",
        "dnf",
        "Network",
        "ip",
        "ping",
        "curl",
        "dig",
        "traceroute",
        "Informational",
        "man",
        "cat",
        "top",
        "ps",
        "du",
        "df\u2022 Text editors",
        "nano",
        "Common configuration files",
        "/etc/passwd",
        "/etc/shadow",
        "/etc/hosts",
        "/etc/fstab",
        "/etc/resolv.conf",
        "OS components",
        "systemd",
        "kernel",
        "bootloader",
        "Root account Given a scenario, install applications according to requirements. .",
        "System requirements for applications",
        "32-bit vs. 64-bit dependent application requirements",
        "Dedicated vs. integrated graphics card",
        "Video random-access memory (VRAM) requirements",
        "RAM requirements",
        "Central processing unit (CPU) requirements",
        "External hardware tokens",
        "Storage requirements",
        "Application to OS compatibility",
        "Distribution methods",
        "Physical media vs. mountable ISO file",
        "Downloadable package",
        "Image deployment\u2022 Impact considerations for new applications",
        "Device",
        "Network",
        "Operation",
        "Business 1.0 | Operating Systems Given a scenario, install and configure cloud-based productivity tools. .",
        "Email systems",
        "Storage",
        "Sync/folder settings",
        "Collaboration tools",
        "Spreadsheets",
        "Videoconferencing",
        "Presentation tools",
        "Word processing tools",
        "Instant messaging\u2022 Identity synchronization",
        "Licensing assignment"
      ]
    },
    "1.11": {
      "domain": "1.0 Operating Systems",
      "title": "Objective 1.11",
      "bullets": [
        "Physical security",
        "Bollards",
        "Access control vestibule",
        "Badge reader",
        "Video surveillance",
        "Alarm systems",
        "Motion sensors",
        "Door locks",
        "Equipment locks",
        "Security guards",
        "Fences",
        "Physical access security",
        "Key fobs",
        "Smart cards",
        "Mobile digital key",
        "Keys \u2212Biometrics \u0563Retina scanner \u0563Fingerprint scanner \u0563Palm print scanner \u0563Facial recognition technology (FRT) \u0563Voice recognition technology",
        "Lighting",
        "Magnetometers",
        "Logical security",
        "Principle of least privilege",
        "Zero Trust model",
        "Access control lists (ACLs)",
        "Multifactor authentication (MFA) \u0563Email \u0563Hardware token \u0563 Authenticator application \u0563 Short Message Service (SMS) \u0563Voice call \u0563Time-based one-time password (TOTP) \u0563One-time password/ passcode (OTP)",
        "Security Assertions Markup Language (SAML)",
        "Single sign-on (SSO)",
        "Just-in-time access \u0563Privileged access management (PAM)",
        "Mobile device management (MDM)",
        "Data loss prevention (DLP)",
        "Identity access management (IAM)",
        "Directory services Given a scenario, configure and apply basic Microsoft Windows OS security settings.",
        "Defender Antivirus",
        "Activate/deactivate",
        "Update definitions",
        "Firewall",
        "Activate/deactivate",
        "Port security",
        "Application security",
        "User and groups",
        "Local vs. Microsoft account",
        "Standard account",
        "Administrator",
        "Guest user",
        "Power user\u2022 Log-in OS options",
        "Username and password",
        "Personal identification number (PIN)",
        "Fingerprint",
        "Facial recognition",
        "SSO",
        "Passwordless/Windows Hello",
        "NTFS vs. share permissions",
        "File and folder attributes",
        "Inheritance",
        "Run as administrator vs. standard user",
        "User Account Control (UAC)\u2022 BitLocker",
        "BitLocker-To-Go",
        "Encrypting File System (EFS)",
        "Active Directory",
        "Joining domain",
        "Assigning log-in script",
        "Moving objects within organizational units",
        "Assigning home folders",
        "Applying Group Policy",
        "Selecting security groups",
        "Configuring folder redirection 2.0 Security Exam Objectives Document Version 4.0",
        "Protocols and encryption",
        "Wi-Fi Protected Access 2 (WPA2)",
        "WPA3",
        "Temporal Key Integrity Protocol (TKIP)",
        "Advanced Encryption Standard (AES)\u2022 Authentication",
        "Remote Authentication Dial- in User Service (RADIUS)",
        "Terminal Access Controller Access- control System (TACACS+)",
        "Kerberos",
        "Multifactor Summarize types of malware and tools/methods for detection, removal, and prevention.",
        "Malware",
        "Trojan",
        "Rootkit",
        "Virus",
        "Spyware",
        "Ransomware",
        "Keylogger",
        "Boot sector virus",
        "Cryptominer",
        "Stalkerware",
        "Fileless\u2022 Adware",
        "Potentially unwanted program (PUP)",
        "Tools and methods",
        "Recovery console",
        "Endpoint detection and response (EDR)",
        "Managed detection and response (MDR)",
        "Extended detection and response (XDR) \u2212Antivirus",
        "Anti-malware",
        "Email security gateway",
        "Software firewalls",
        "User education regarding common threats \u0563Antiphishing training",
        "OS reinstallation Compare and contrast common social engineering attacks, threats, and vulnerabilities.",
        "Social engineering",
        "Phishing \u0563Vishing \u0563Smishing \u0563 QR code phishing \u0563 Spear phishing \u0563 Whaling",
        "Shoulder surfing",
        "Tailgating",
        "Impersonation",
        "Dumpster diving \u2022 Threats",
        "Denial of service (DoS)",
        "Distributed denial of service (DDoS)",
        "Evil twin",
        "Zero-day attack",
        "Spoofing",
        "On-path attack",
        "Brute-force attack",
        "Dictionary attack",
        "Insider threat",
        "Structured Query Language (SQL) injection \u2212Cross-site scripting (XSS)",
        "Business email compromise (BEC)",
        "Supply chain/pipeline attack",
        "Vulnerabilities",
        "Non-compliant systems",
        "Unpatched systems",
        "Unprotected systems (missing antivirus/missing firewall)",
        "EOL",
        "Bring your own device (BYOD) 2.0 | Security"
      ]
    },
    "2.5": {
      "domain": "2.0 Security",
      "title": "Objective 2.5",
      "bullets": [
        "Data-at-rest encryption",
        "Password considerations",
        "Length",
        "Character types",
        "Uniqueness",
        "Complexity",
        "Expiration",
        "Basic input/output system (BIOS)/ Unified Extensible Firmware Interface (UEFI) passwords\u2022 End-user best practices",
        "Use screensaver locks",
        "Log off when not in use",
        "Secure/protect critical hardware (e.g., laptops)",
        "Secure personally identifiable information (PII) and passwords",
        "Use password managers",
        "Account management",
        "Restrict user permissions \u2212Restrict log-in times",
        "Disable guest account",
        "Use failed attempts lockout",
        "Use timeout/screen lock",
        "Apply account expiration dates",
        "Change default administrator\u2019s user account/password",
        "Disable AutoRun",
        "Disable unused services Given a scenario, apply common methods for securing mobile devices.",
        "Hardening techniques",
        "Device encryption",
        "Screen locks \u0563 Facial recognition \u0563PIN codes \u0563 Fingerprint \u0563 Pattern \u0563 Swipe",
        "Configuration profiles\u2022 Patch management",
        "OS updates",
        "Application updates",
        "Endpoint security software",
        "Antivirus",
        "Anti-malware",
        "Content filtering\u2022 Locator applications",
        "Remote wipes",
        "Remote backup applications",
        "Failed log-in attempts restrictions",
        "Policies and procedures",
        "MDM",
        "BYOD vs. corporate-owned devices",
        "Profile security requirements Compare and contrast common data destruction and disposal methods.",
        "Physical destruction of hard drives",
        "Drilling",
        "Shredding",
        "Degaussing",
        "Incineration\u2022 Recycling or repurposing best practices",
        "Erasing/wiping",
        "Low-level formatting",
        "Standard formatting\u2022 Outsourcing concepts",
        "Third-party vendor",
        "Certification of destruction/recycling",
        "Regulatory and environmental requirements 2.0 | Security Exam Objectives Document Version 4.0",
        "Router settings",
        "Change default passwords",
        "IP filtering",
        "Firmware updates",
        "Content filtering",
        "Physical placement/secure locations",
        "Universal Plug and Play (UPnP) \u2212Screened subnet",
        "Configure secure management access",
        "Wireless specific",
        "Changing the service set identifier (SSID) \u2212Disabling SSID broadcast",
        "Encryption settings",
        "Configuring guest access",
        "Firewall settings",
        "Disabling unused ports",
        "Port forwarding/mapping2.10 2.0 | Security Given a scenario, configure relevant security settings in a browser.",
        "Browser download/installation",
        "Trusted sources \u0563Hashing",
        "Untrusted sources",
        "Browser patching",
        "Extensions and plug-ins",
        "Trusted sources",
        "Untrusted sources\u2022 Password managers",
        "Secure connections/ sites\u2013valid certificates",
        "Settings",
        "Pop-up blocker",
        "Clearing browsing data",
        "Clearing cache",
        "Private-browsing mode",
        "Sign-in/browser data synchronization \u2212Ad blockers",
        "Proxy",
        "Secure DNS",
        "Browser feature management",
        "Enable/disable \u0563Plug-ins \u0563Extensions \u0563Features"
      ]
    },
    "2.11": {
      "domain": "2.0 Security",
      "title": "Objective 2.11",
      "bullets": [
        "Blue screen of death (BSOD)",
        "Degraded performance",
        "Boot issues",
        "Frequent shutdowns\u2022 Services not starting",
        "Applications crashing",
        "Low memory warnings",
        "USB controller resource warnings\u2022 System instability",
        "No OS found",
        "Slow profile load",
        "Time drift Given a scenario, troubleshoot common mobile OS and application issues.",
        "Application fails to launch",
        "Application fails to close/crashes",
        "Application fails to update",
        "Application fails to install",
        "Slow to respond",
        "OS fails to update",
        "Battery life issues\u2022 Random reboots",
        "Connectivity issues",
        "Bluetooth",
        "Wi-Fi",
        "Near-field communication (NFC)",
        "Screen does not autorotate 3.0 Software Troubleshooting Given a scenario, troubleshoot common mobile OS and application security issues.",
        "Security concerns",
        "Application source/unofficial application stores",
        "Developer mode",
        "Root access/jailbreak",
        "Unauthorized/malicious application \u0563 Application spoofing\u2022 Common symptoms",
        "High network traffic",
        "Degraded response time",
        "Data-usage limit notification",
        "Limited internet connectivity",
        "No internet connectivity",
        "High number of ads \u2212Fake security warnings",
        "Unexpected application behavior",
        "Leaked personal files/data"
      ]
    },
    "3.2": {
      "domain": "3.0 Software Troubleshooting",
      "title": "Given a scenario, troubleshoot common personal computer (PC) security issues.",
      "bullets": [
        "Common symptoms",
        "Unable to access the network",
        "Desktop alerts",
        "False alerts regarding antivirus protection",
        "Altered system or personal files \u0563 Missing/renamed files \u0563Inability to access files",
        "Unwanted notifications within the OS",
        "OS updates failures\u2022 Browser-related symptoms",
        "Random/frequent pop-ups",
        "Certificate warnings",
        "Redirection",
        "Degraded browser performance"
      ]
    },
    "3.4": {
      "domain": "3.0 Software Troubleshooting",
      "title": "Objective 3.4",
      "bullets": [
        "Ticketing systems",
        "User information",
        "Device information",
        "Description of issues",
        "Categories",
        "Severity",
        "Escalation levels",
        "Clear, concise written communication \u0563Issue description \u0563Progress notes \u0563Issue resolution\u2022 Asset management",
        "Inventory lists",
        "Configuration management database (CMDB)",
        "Asset tags and IDs",
        "Procurement life cycle",
        "Warranty and licensing",
        "Assigned users",
        "Types of documents",
        "Incident reports \u2212Standard operating procedures (SOPs) \u0563 Software package custom installation procedure",
        "New user/onboarding setup checklist",
        "User off-boarding checklist",
        "Service-level agreements (SLAs) \u0563Internal \u0563External/third-party",
        "Knowledge base/articles Given a scenario, apply change management procedures.",
        "Documented business processes",
        "Rollback plan",
        "Backup plan",
        "Sandbox testing",
        "Responsible staff members",
        "Change management",
        "Request forms",
        "Purpose of the change \u2212Scope of the change",
        "Change type \u0563Standard change \u0563Normal change \u0563Emergency change",
        "Date and time of change \u0563Change freeze \u0563Maintenance windows",
        "Affected systems/impact \u2212Risk analysis \u0563Risk level",
        "Change board approvals",
        "Implementation",
        "Peer review",
        "End-user acceptance 4.0 Operational Procedures"
      ]
    },
    "4.2": {
      "domain": "4.0 Operational Procedures",
      "title": "Given a scenario, implement workstation backup and recovery methods.",
      "bullets": [
        "Backup",
        "Full",
        "Incremental",
        "Differential",
        "Synthetic full\u2022 Recovery",
        "In-place/overwrite",
        "Alternative location",
        "Backup testing",
        "Frequency\u2022 Backup rotation schemes",
        "Onsite vs. offsite",
        "Grandfather-father-son (GFS)",
        "3-2-1 backup rule"
      ]
    },
    "4.3": {
      "domain": "4.0 Operational Procedures",
      "title": "Objective 4.3",
      "bullets": [
        "Electrostatic discharge (ESD) straps",
        "ESD mats",
        "Electrical safety",
        "Equipment grounding",
        "Proper component handling and storage",
        "Cable management",
        "Antistatic bags\u2022 Compliance with government regulations",
        "Personal safety",
        "Disconnect power before repairing PC",
        "Lifting techniques",
        "Fire safety",
        "Safety goggles",
        "Air filter mask Summarize environmental impacts and local environment controls.",
        "Material safety data sheet (MSDS) documentation for handling and disposal",
        "Proper battery disposal",
        "Proper toner disposal",
        "Proper disposal of other devices and assets",
        "Temperature, humidity-level awareness, and proper ventilation",
        "Location/equipment placement",
        "Dust cleanup",
        "Compressed air/vacuums\u2022 Power surges, brownouts, and blackouts",
        "Uninterruptible power supply (UPS)",
        "Surge suppressor Explain the importance of prohibited content/activity and privacy, licensing, and policy concepts.",
        "Incident response",
        "Chain of custody",
        "Informing management/law enforcement as necessary",
        "Copy of drive (data integrity and preservation)",
        "Incident documentation",
        "Order of volatility",
        "Licensing/digital rights management (DRM)/ end-user license agreement (EULA)",
        "Valid licenses",
        "Perpetual license agreement",
        "Personal-use license vs. corporate-use license",
        "Open-source license\u2022 Non-disclosure agreement (NDA)/mutual non-disclosure agreement (MNDA)",
        "Regulated data",
        "Credit card payment information",
        "Personal government-issued information",
        "PII",
        "Healthcare data",
        "Data retention requirements",
        "Acceptable use policy (AUP)",
        "Regulatory and business compliance requirements",
        "Splash screens 4.0 | Operational Procedures"
      ]
    },
    "4.6": {
      "domain": "4.0 Operational Procedures",
      "title": "Objective 4.6",
      "bullets": [
        "Present a professional appearance and wear appropriate attire.",
        "Match the required attire of the given environment. \u0563 Formal \u0563 Business casual",
        "Use proper language and avoid jargon, acronyms, and slang, when applicable.",
        "Maintain a positive attitude/ project confidence.",
        "Actively listen and avoid interrupting the customer.",
        "Be culturally sensitive.",
        "Use appropriate professional titles and designations, when applicable.\u2022 Be on time (if late, contact the customer).",
        "Avoid distractions.",
        "Personal calls",
        "Texting/social media sites",
        "Personal interruptions",
        "Appropriately deal with difficult customers or situations.",
        "Do not argue with customer and/or be defensive.",
        "Avoid dismissing customer issues.",
        "Avoid being judgmental.",
        "Clarify customer statements (i.e., ask open-ended questions to narrow the scope of the issue, restate the issue, or question to verify understanding). \u2212Use discretion and professionalism when discussing experiences/encounters.",
        "Set and meet expectations/ timeline and communicate status with the customer.",
        "Offer repair/replacement options, as needed.",
        "Provide proper documentation on the services provided.",
        "Follow up with customer/user at a later date to verify satisfaction.",
        "Appropriately handle customers\u2019 confidential and private materials.",
        "Located on a computer, desktop, printer, etc. Explain the basics of scripting.",
        "Script file types",
        ".bat",
        ".ps1",
        ".vbs",
        ".sh",
        ".js",
        ".py\u2022 Use cases for scripting",
        "Basic automation",
        "Restarting machines",
        "Remapping network drives",
        "Installation of applications",
        "Automated backups",
        "Gathering of information/data",
        "Initiating updates\u2022 Other considerations when using scripts",
        "Unintentionally introducing malware",
        "Inadvertently changing system settings",
        "Browser or system crashes due to mishandling of resources Given a scenario, use remote access technologies.",
        "Methods/tools",
        "RDP",
        "VPN",
        "Virtual network computer (VNC)",
        "Secure Shell (SSH)",
        "Remote monitoring and management (RMM) \u2212Simple Protocol for Independent Computing Environments (SPICE)",
        "Windows Remote Management (WinRM)",
        "Third-party tools \u0563 Screen-sharing software \u0563Videoconferencing software \u0563 File transfer software \u0563 Desktop management software",
        "Security considerations of each access method 4.0 | Operational Procedures Explain basic concepts related to artificial intelligence (AI).",
        "Application integration",
        "Policy",
        "Appropriate use",
        "Plagiarism\u2022 Limitations",
        "Bias",
        "Hallucinations",
        "Accuracy\u2022 Private vs. public",
        "Data security",
        "Data source",
        "Data privacy"
      ]
    },
    "4.10": {
      "domain": "4.0 Operational Procedures",
      "title": "Objective 4.10",
      "bullets": [
        "Apple tablet/smartphone",
        "Android tablet/smartphone",
        "Windows tablet",
        "Chromebook",
        "Windows laptop/Mac laptop/ Linux laptop",
        "Windows desktop/Mac desktop/ Linux desktop",
        "Windows server with Active Directory and Print Manager",
        "Monitors",
        "Projectors",
        "SOHO router/switch",
        "Access point (AP)",
        "Voice over Internet Protocol (VoIP) phone",
        "Printer",
        "Laser/inkjet",
        "Wireless",
        "3-D printer",
        "Thermal",
        "Surge suppressor",
        "UPS",
        "Smart devices [Internet of Things (IoT) devices]",
        "Server with a hypervisor",
        "Punchdown block",
        "Patch panel",
        "Webcams",
        "Speakers",
        "MicrophonesSPARE PARTS/HARDWARE",
        "Motherboards",
        "RAM",
        "Hard drives",
        "Power supplies",
        "Video cards",
        "Sounds cards",
        "Network cards",
        "Wireless network interface cards (NICs)",
        "Fans/cooling devices/heat sink",
        "CPUs",
        "Assorted connectors/cables",
        "USB",
        "High-Definition Multimedia Interface (HDMI)",
        "DisplayPort",
        "Digital Visual Interface (DVI)",
        "Video Graphics Array (VGA)",
        "Adapters",
        "Bluetooth adapter",
        "Network cables",
        "Unterminated network cable/connectors",
        "AC adapters",
        "Optical drives",
        "Screws/stand-offs",
        "Cases",
        "Maintenance kit",
        "Mice/keyboards",
        "Keyboard-Video-Mouse (KVM)",
        "Console cable",
        "Solid-state drive (SSD)TOOLS",
        "Screwdrivers",
        "Multimeter",
        "Wire cutters",
        "Punchdown tool",
        "Crimper",
        "Power supply tester",
        "Cable stripper",
        "Standard technician toolkit",
        "ESD strap",
        "Thermal paste",
        "Cable tester",
        "Cable toner",
        "Wi-Fi analyzer",
        "Serial Advanced Technology Attachment (SATA) to USB connectors SOFTWARE",
        "Operating systems",
        "LinuxCompTIA has included this sample list of hardware and software to assist candidates as they prepare for the A+ Core 2 (220-1202) certification exam. This list may also be helpful for training companies that wish to create a lab component for their training offering. The bulleted lists below each topic are sample lists and are not exhaustive.CompTIA A+ Core 2 (220-1202) Hardware and Software List \u00a9 2024 CompTIA, Inc., used under license by CompTIA, Inc. All rights reserved. All certification programs and education related to such programs are operated exclusively by CompTIA, Inc. CompTIA is a registered trademark of CompTIA, Inc. in the U.S. and internationally. Other brands and company names mentioned herein may be trademarks or service marks of CompTIA, Inc. or of their respective owners. Reproduction or dissemination prohibited without the written consent of CompTIA, Inc. Printed in the U.S. 11273-May2024"
      ]
    }
  }
} as const;
